version: '2'
services:
  nginx:
    image: nginx:latest
    container_name: reverse_proxy
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "9090:9090"
    depends_on:
      - helloworld1
      - helloworld2

  helloworld1:
    image: api
    container_name: helloworld1
    ports:
      - "8088:8080"

  helloworld2:
    image: api
    container_name: helloworld2
    ports:
      - "8089:8080"